# Generated by Django 3.2.8 on 2021-11-06 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_comment_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('current_bid', models.IntegerField(default='0')),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_nameo', to='auctions.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_prodos', to=settings.AUTH_USER_MODEL)),
                ('watchedby', models.ManyToManyField(blank=True, related_name='watchedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
