# Generated by Django 3.2.8 on 2021-11-06 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_usero', to=settings.AUTH_USER_MODEL)),
                ('watchedbys', models.ManyToManyField(blank=True, related_name='watchedbys', to='auctions.Product')),
            ],
        ),
    ]
