# Generated by Django 3.2.8 on 2021-11-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_usero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usero',
        ),
    ]
