# Generated by Django 3.2.8 on 2021-11-06 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_delete_usero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='watchedby',
        ),
        migrations.AddField(
            model_name='product',
            name='watchedby',
            field=models.ManyToManyField(blank=True, related_name='watchedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='watchedbys',
            field=models.ManyToManyField(blank=True, related_name='watchedbys', to=settings.AUTH_USER_MODEL),
        ),
    ]
