# Generated by Django 3.2.8 on 2021-11-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211106_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
