# Generated by Django 3.2.8 on 2021-11-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_producto_usero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usero',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usero',
            name='watchedbys',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Usero',
        ),
    ]
