# Generated by Django 3.2.8 on 2021-11-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211106_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
